site_name: Starting Line Productions Shop Guide
site_url: https://guide.startinglineproductions.com
theme:
  name: material
  font:
    text: Atkinson Hyperlegible
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_url: https://github.com/ReachableCEO/STLPublicShopGuide
repo_name: reachableceo/STLPublicShopGuide
edit_uri: edit/main/docs/docs/
plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - footnotes
nav:
  - Home: index.md
  - Version History: version-history.md
  - Shop Health / Safety / Security information: shss.md
  - First Aid: first-aid.md
  - Emergency Action Plan: emactplan.md
  - Workstation Software (common): common-software.md
  - E3ds shop overview: e3ds-shop-overview.md
  - E3ds PC Hardware/Software and Peripherals And Equipment: e3ds-pchwswp.md
  - E3ds Tools: e3ds-tools.md
  - E3ds Supplies: e3ds-supplies.md
  - Cleanfab Shop Overview: cleanfab-shop-overview.md
  - Cleanfab Tools: cleanfab-tools.md
  - Cleanfab Equipment: cleanfab-equipment.md
  - Cleanfab Supplies: cleanfab-supplies.md
  - Dirtyfab Shop Overview: dirtyfab-shopoverview.md
  - Dirtyfab PC Hardware/Software and Peripherals: dirtyfab-pchwswp.md
  - Dirtyfab Tools: dirtyfab-tools.md
  - Dirtyfab Equipment: dirtyfab-equipment.md
  - Dirtyfab Supplies: dirtyfab-supplies.md
  - Kitchen Overview: kitchen-overview.md
  - Kitchen Tools: kitchen-tools.md
  - Kitchen Equipment: kitchen-equipment.md
  - HPCLab Overview: hpclab-overview.md
  - HPCLab Inventory: hpclab-inventory.md
  - RackRental overview: rackrental-overview.md
  - RackRental inventory: rackrental-inventory.md